import React from 'react';

export default function PrivacyPolicy() {
  return (
    <div className="py-12 sm:py-20 max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 space-y-8">
      <h1 className="font-heading font-extrabold text-3xl sm:text-4xl text-navy">Privacy Policy</h1>
      <div className="prose prose-slate text-sm sm:text-base leading-relaxed space-y-6 text-slate-700">
        <p>
          At <strong>Smile & Dental Clinic</strong> (led by Dr. Ananyo Mandal, Burdwan), we hold your medical confidentiality and personal privacy to the highest standard.
        </p>
        <h3 className="font-heading font-bold text-lg text-navy">1. Information We Collect</h3>
        <p>
          We collect personal identification information including your full name, mobile number, optional email address, requested appointment date, and treatment symptoms solely for the purpose of booking and administering dental appointments.
        </p>
        <h3 className="font-heading font-bold text-lg text-navy">2. How Information is Used</h3>
        <p>
          Your information is utilized exclusively to manage scheduling, communicate appointment status changes via push notifications or telephone calls, and maintain diagnostic clinical records. We do not sell, rent, or trade your data to third parties.
        </p>
        <h3 className="font-heading font-bold text-lg text-navy">3. Web Push Notifications</h3>
        <p>
          When you enable push notifications, a unique anonymous Firebase Cloud Messaging device registration token is generated by your browser. This token is used solely to alert you when Dr. Mandal confirms or updates your appointment status.
        </p>
        <h3 className="font-heading font-bold text-lg text-navy">4. Contact Us</h3>
        <p>
          If you have questions regarding this Privacy Policy, please contact Dr. Ananyo Mandal at <strong>mandalananyo@gmail.com</strong> or phone <strong>9903424407</strong>.
        </p>
      </div>
    </div>
  );
}
